name: Deploy

on:
  push:
    branches:
      - docs

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.2"
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master
          path: master
      - name: Setup git repo
        run: |
          git config --global user.email "masaki.arizuka+ci@gmail.com"
          git config --global user.name "ci@github"
      - run: npm install
      - run: npm run deploy