name: Deploy

on:
  push:
    branches:
      - docs

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.2"
      - name: Create master worktree
        run: git worktree add -b out master
      - run: npm install
      - run: npm run deploy